### ISSUE TITLE
replace glutin by azul

### ISSUE THREAD

**Issue by gogo2464** [j-selby/oxidgb#1]
Glutin is a very low level library for GUI. Do we really need that? I suggest to replace it by azul.

Let me know your opinion.

**Comment by gogo2464** [comment]
glutin may be necessary. You need to emulate a screen after all.


I just read this tutorial https://bugzmanov.github.io/nes_ebook/chapter_3_4.html?highlight=sdl#running-our-first-game you can close this issue.

**Comment by gogo2464** [comment]
But add an azul wrapper could be great.

**Comment by j-selby** [comment]
Hi! Not sure what use-case you are looking for in terms of this - I'm interested in swapping out the glutin frontend for a [pixels](https://github.com/parasyte/pixels) one, but is there some specific set of functionality that azul would help with? It does add a binary library dependency which complicates the build process significantly for the emulator which I'm not sure is suitable, and I don't believe it has an easy way to do a hardware-accelerated framebuffer.

**Comment by gogo2464** [comment]
There is no more functionalities in azul than `glutin` or `pixels`.  It is just more high level.  The best option could be to use pixel wraped by azul. I do not know if it is possible.

**Comment by j-selby** [comment]
Given the small amount of code needed, and the relative control enabled by the `glutin` approach, I don't believe there is value in azul - a higher level API doesn't really mean much when it will just make control harder. Given the implementation-independent part of the core people can port it around as needed.

I appreciate the recommendation, but given this I'll be closing this issue.
