### ISSUE TITLE
write a remote gdb server

### ISSUE THREAD

**Issue by gogo2464** [j-selby/oxidgb#2]
I posted this in another repo: https://github.com/MarkMcCaskey/rusty-boy/issues/84#issue-860713576

> Currently there is no remote debugger for game boy because of the architecture.
> 
> There is for game boy advance.
> 
> It is embarassing because people could need to connect ghidra or radare2 or IDA pro on an emulator.
> 
> It could be great if we create a new one. We will be the first.
> 
> I personally need it.
> 
> Assign me on this issue.

Sadly their debugger is not finished. I can not start the remote debugger. Then I will start here.

Assign me in this issue.

**Comment by gogo2464** [comment]
Edit : It seems that the debugging process is not implemented at all in oxidgb. Sorry I will finish to see for rusty-boy in order to write a remote gdb server in oxidgb.

**Comment by j-selby** [comment]
Appreciate you raising this issue for this one.

There is a hook a caller can use into the library for debugging purposes - <https://github.com/j-selby/oxidgb/blob/master/core/src/cpu/mod.rs#L252>. You can see a command-line example of this in the glutin frontend: <https://github.com/j-selby/oxidgb/blob/master/glutin_frontend/src/debugger.rs>.

This is called on each instruction if the `debugger` feature is enabled, which would allow for the implementation of a GDB frontend. It might need tweaking but given it provides instruction-by-instruction hooks this shouldn't be too substantial.

Stuff this would require:

- Interface to (likely) https://docs.rs/gdbstub for the (glutin/libretro) frontend itself - this would handle the "remote" part of this.
- Implement gdbstub's Target trait based on this debugging hook.

**Comment by gogo2464** [comment]
I found an example of how to do it in an emulator here: [https://github.com/daniel5151/gdbstub/blob/master/examples/armv4t/main.rs#L46](https://github.com/daniel5151/gdbstub/blob/master/examples/armv4t/main.rs#L46). It will be very useful.



Currently the debugger exists but does not compile. As far as I try I did `cargo run --features=debugger --release` and I got:

```
error[E0277]: the trait bound `&mut Debugger: GameboyDebugger` is not satisfied
   --> core/src/cpu/mod.rs:157:26
    |
157 |         while !self.tick(&mut debugger) {}
    |                          -^^^^^^^^^^^^
    |                          |
    |                          the trait `GameboyDebugger` is not implemented for `&mut Debugger`
    |                          help: consider removing the leading `&`-reference

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `oxidgb_core`
```

So first I try to solve this issue. Then I will see how to debug the rom and then I will write the remote gdb server.

**Comment by gogo2464** [comment]
To avoid conflicts you could get a look here: https://github.com/j-selby/oxidgb/pull/3

**Comment by gogo2464** [comment]
Is the code supposed to work? I saw the mention broken code on the readme.

**Comment by j-selby** [comment]
The broken code reference in the README is meant to be a joke. The debugger was broken by a recent commit however - 50010ed0008f1afde041a0c698f4492eadbeab3f fixes it. Compile the Glutin frontend with `--features debugger` in order to use it.

**Comment by gogo2464** [comment]
I do not think there is a difference with `cargo run --features=debugger --release`. The command `cargo run --release --features debugger` also returns:

```
error[E0277]: the trait bound `&mut Debugger: GameboyDebugger` is not satisfied
   --> core/src/cpu/mod.rs:157:26
    |
157 |         while !self.tick(&mut debugger) {}
    |                          -^^^^^^^^^^^^
    |                          |
    |                          the trait `GameboyDebugger` is not implemented for `&mut Debugger`
    |                          help: consider removing the leading `&`-reference

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `oxidgb_core`

To learn more, run the command again with --verbose.
```

I am on debian 10 on virtualbox.
I am sorry I do not think the code compiles on any OS.

**Comment by gogo2464** [comment]
This is why I open this PR: https://github.com/j-selby/oxidgb/pull/3

**Comment by j-selby** [comment]
`I am sorry I do not think the code compiles on any OS.`

As referenced, pull the latest commit from the repository - this will solve your issue. It compiles successfully on multiple platforms.

**Comment by gogo2464** [comment]
@j-selby really I did 

```
git checkout master;
git pull origin;
cargo run --features debugger;
```

and still the error:

error[E0061]: this function takes 1 argument but 0 arguments were supplied
   --> libretro_frontend/src/lib.rs:155:13
    |
155 |         cpu.run();
    |             ^^^- supplied 0 arguments
    |             |
    |             expected 1 argument
    |
note: associated function defined here
   --> /TRUNCATED/src/cpu/mod.rs:149:12
    |
149 |     pub fn run<#[cfg(feature = "debugger")] Debugger: GameboyDebugger>(
    |            ^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
error: could not compile `oxidgb_libretro`

To learn more, run the command again with --verbose.

**Comment by gogo2464** [comment]
@j-selby then can you tell me more on your environment?

**Comment by j-selby** [comment]
Hi, couple of things:

- The LibRetro frontend doesn't support the debugger given that it doesn't really have a command line interface. Use the Glutin frontend instead.
- Make sure you are running `cargo` in the `glutin_frontend` directory.

If this continues to be an issue, remove the libretro frontend from the root Cargo.toml file to avoid there being any dependency.

I compile this on Windows: `nightly-x86_64-pc-windows-msvc`

**Comment by gogo2464** [comment]
I can not debug this rom:

[crack_rom.zip](https://github.com/j-selby/oxidgb/files/6359608/crack_rom.zip)

I see the top of the emulator windows with no screen for the rom. The top is actually frozen. Maybe the rom requires the debugging symbols.

I still can open it with no debugging.


```
[17:51:32] [glutin_frontend/src/main.rs:87] [INFO]: Oxidgb v0.1
[17:51:32] [glutin_frontend/src/main.rs:134] [INFO]: Opening ROM: ROM
[17:51:32] [glutin_frontend/src/main.rs:136] [INFO]: Emulation state memory usage: 368
[17:51:34] [/home/TRUNCATED/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.12.2/src/window/concept_frame.rs:658] [ERROR]: No font could be found
[17:51:34] [glutin_frontend/src/main.rs:189] [INFO]: OpenGL version: 3.3 (Core Profile) Mesa 18.3.6
0000 @ 0100
Debugger:
i
af = 01B0
bc = 0013
de = 00D8
hl = 014D
sp = FFFE
pc = 0100

```

**Comment by j-selby** [comment]
As discussed in Discord, this is beyond the scope of the project - let me know if there is a significant need for this however!

**Comment by gogo2464** [comment]
> As discussed in Discord, this is beyond the scope of the project - let me know if there is a significant need for this however!

I am disapointed. I believed you told you appreciated for this one.
I want to come back to bring this feature.

Do you want so? :)

**Comment by gogo2464** [comment]
@j-selby Could you tell me please?

**Comment by j-selby** [comment]
From Discord:

```Hey - i'm not interested in opening my DMs, sorry - with respect, I can't help you on this one.

Given that my core code/the debugger is fairly old it really doesn't have the love that I would want to put into it, and bringing it up to a clean state is not something I'm interested in currently as I'm working on other projects, and it wouldn't have significant value for open source software generally given that there are more sophisticated Rust emulators out there (even if they don't have the same kind of debugger).

I am happy to answer high-level questions about what I designed, but its read-only from my perspective and is more designed as reference material for others.

Additionally, I don't have the time or resources to step you through some of this basic functionality especially given that emulation can be a complex topic - again, I apologise for this.

I do however appreciate the support and interest in my work, and I apologise that I can't help you further.
```

I'm not interested in turning this into a major emulator - this is a testbed for different ideas, particularly in the embedded domain and isn't really aimed at general consumption.

If you want to keep working on this, please take what I have and do it in a fork - I don't want to be adding interfaces that I personally aren't going to be validating/using.

Thanks again for the interest and support, but I won't be accepting a GDB frontend for this - it is way too complex and overkill for what I want out of this.
