### ISSUE TITLE
Set an option to debug instead of use a feature

### ISSUE THREAD

**Issue by gogo2464** [j-selby/oxidgb#6]
If we want to swap between run and debug we can only recompile. I also think it is a bad pratice all these `#[cfg(feature = "debugger")]` in the code because we loose in readability. 

So I suggest to build a full binary with all functionality and then use an option `--debug` or `-d` instead of recompiling everything.

Another option could be to still use `#[cfg(feature = "debugger")]` but on a full file.

You can assign me I am going to start. I will do the first idea.

**Comment by gogo2464** [comment]
The idea is to be able to run with no debug when the program is compiled with debugging feature.

**Comment by j-selby** [comment]
See #7
