### ISSUE TITLE
split the file core/src/cpu/mod.rs into two distinct files: debugger.rs and cpu.rs

### ISSUE THREAD

**Issue by gogo2464** [j-selby/oxidgb#8]
Currently the file mod.rs contains a debugger and the cpu definition.

This is particulary embarassing for readability because there are tons of #[cfg(feature = "debugger")] in the file. It would be better to have two separated files: debugger.rs and cpu.rs and then in mod.rs we simply do

```
#[cfg(not(feature = "debugger"))]
mod cpu;
#[cfg(feature = "debugger")]
mod debugger;
```

Also note that this is not incoherent with this issue : https://github.com/j-selby/oxidgb/issues/6 because we could set the debugger only when the feature is enabled and ignore the feature with a command line option.

**Comment by j-selby** [comment]
As per my feedback in #7, I feel like a larger change needs to occur here. Closing based on that.
